.. Directives
.. |HRM_VERSION|            replace:: 3.8.x
.. |note|                   image:: images/note.png
.. |linux|                  image:: images/linux_logo_22x22.png
.. |centos|                 image:: images/centos_logo_22x22.png
.. |debian|                 image:: images/debian_logo_22x22.png
.. |ubuntu|                 image:: images/ubuntu_logo_22x22.png
.. |fedora|                 image:: images/fedora_logo_22x22.png
.. |macosx|                 image:: images/apple_logo_22x22.png
.. |github|                 image:: images/github_logo_22x22.png
.. |ServersGPUs22x22|       image:: images/ServersGPUs22x22.png
.. |ServersGPUsScreenshot|  image:: images/ServersGPUsScreenshot.png
.. |script_install_1|       image:: images/script_install_1.png
.. |script_install_2|       image:: images/script_install_2.png
.. |script_install_3|       image:: images/script_install_3.png
.. |script_install_4|       image:: images/script_install_4.png
.. |script_install_db_1|    image:: images/script_install_db_1.png
.. |script_install_db_2|    image:: images/script_install_db_2.png
.. |script_install_db_3|    image:: images/script_install_db_3.png
.. |script_install_db_4|    image:: images/script_install_db_4.png
.. |script_install_db_5|    image:: images/script_install_db_5.png
.. |script_install_db_6|    image:: images/script_install_db_6.png
.. |script_install_db_7|    image:: images/script_install_db_7.png
.. |script_install_db_8|    image:: images/script_install_db_8.png
.. |script_install_db_9|    image:: images/script_install_db_9.png
.. |script_install_db_10|   image:: images/script_install_db_10.png
.. |ge|                     unicode:: U+02265 .. GREATER THAN OR EQUAL TO
