.. Directives
.. |HRM_VERSION|            replace:: 3.5.x
.. |note|                   image:: images/note.png
.. |linux|                  image:: images/linux_logo_22x22.png
.. |centos|                 image:: images/centos_logo_22x22.png
.. |debian|                 image:: images/debian_logo_22x22.png
.. |ubuntu|                 image:: images/ubuntu_logo_22x22.png
.. |fedora|                 image:: images/fedora_logo_22x22.png
.. |macosx|                 image:: images/apple_logo_22x22.png
.. |github|                 image:: images/github_logo_22x22.png
.. |ServersGPUs22x22|       image:: images/ServersGPUs22x22.png
.. |ServersGPUsScreenshot|  image:: images/ServersGPUsScreenshot.png
.. |ge|                     unicode:: U+02265 .. GREATER THAN OR EQUAL TO
