.. Directives
.. |HRM_VERSION|    replace:: 3.2.1
.. |note|           image:: images/note.png
.. |linux|          image:: images/linux_logo_22x22.png
.. |ubuntu|         image:: images/ubuntu_logo_22x22.png
.. |fedora|         image:: images/fedora_logo_22x22.png
.. |macosx|         image:: images/apple_logo_22x22.png
.. |github|         image:: images/github_logo_22x22.png
.. |ge|             unicode:: U+02265 .. GREATER THAN OR EQUAL TO
